### ISSUE TITLE
[dbc] - PostgreSQL

### ISSUE THREAD

**Issue by BuffePOK** [logistics-ecosystem/order-management#1]
#### Tables: 
 - Orders History
 - Accepted Orders

#### Tasks:
 - [x] Create DB
 - [x] Create DTO for orders
 - [x] Adding new history order
 - [x] Get orders by filters
 - [x] Get accepted orders by filters
 - [x] Get order by id

#### Estimated time: 
| Dmytro | Sashko | Maksym |
| -- | -- | -- |
| 3h | 2h | 2h |

Average: **2h**
