### ISSUE TITLE
[dbc] - MongoDB

### ISSUE THREAD

**Issue by BuffePOK** [logistics-ecosystem/order-management#2]
#### Data Types: 
 - Available Orders
 - Deadline Checklist

#### Tasks:
 - [x] Create DTO for orders
 - [x] Adding new available orders
 - [x] Auto check deadline orders
 - [x] Get all orders-list
 - [x] Get orders by filters
 - [x] Get order by id
 - [x] Delete order by id

#### Estimated time: 
| Dmytro | Sashko | Maksym |
| -- | -- | -- |
| 3h | 4h | 3h |

Average: **3h**

**Comment by BuffePOK** [comment]
Hello

Please, send [code here](https://github.com/logistics-ecosystem/order-management/tree/2-dbc---mongodb)
I also waiting for your pull-request :)

**Comment by BuffePOK** [comment]
Hello, @OPapHub 

Please, send [code here](https://github.com/logistics-ecosystem/order-management/tree/2-dbc---mongodb)
I also waiting for your pull-request :)

**Comment by ghost** [comment]
Thank you, already updated and did pull-request

**Comment by BuffePOK** [comment]
Dear @OPapHub,
Thank you for coordination 👍
